pid: /var/www/cap_test/shared/pids/thin.pid
address: 127.0.0.1
port: 3000
timeout: 30
wait: 30
log: /var/www/cap_test/shared/log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
# threaded: true
# no-epoll: true
daemonize: true
socket: /var/www/cap_test/shared/sockets/thin.sock
chdir: /var/www/cap_test/current
tag: cap_test
